
spring:
  boot:
    admin:
      client:
        url: http://localhost:8084
  datasource:
    url: jdbc:mysql://172.16.3.150:3306/oomallother?serverTimezone=GMT%2B8
    username: dbuser
    password: 123456
    druid:
      stat-view-servlet:
        login-username: admin
        login-password: 123456
        enabled: true
        url-pattern: /druid/*
  redis:
    # Redis服务器地址
    host: 172.16.2.67
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码
    password: 123456

  cloud:
    nacos:
      discovery:
        server-addr: 172.16.2.199:8848