other-ip:
  customer: 172.16.2.214:8081
  address: 172.16.0.69:8082
  advertisement: 172.16.2.96:8083
  aftersale: 172.16.0.69:8084
  cart: 172.16.1.64:8085
  favorite: 172.16.1.250:8086
  footprint: 172.16.1.250:8087
  share: 172.16.0.69:8088
  timesegment: 172.16.2.96:8089
order-ip:
  order: 172.16.3.169:8084
  payment: 172.16.3.169:8085
  freight: 172.16.3.169:8083
goods-ip: 172.16.1.181:8080
server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - HEAD
              - OPTIONS
      routes:
        - id: login
          uri: http://${other-ip.customer}
          predicates:
            - Path=/users/login,/users
            - Method=POST
          filters:
            - PrefixPath=/user

        - id: adminuser
            uri: http://${other-ip.customer}
            predicates:
              - Path=/users/state
            filters:
              - PrefixPath=/user

        - id: adminusers
          uri: http://${other-ip.customer}
          predicates:
            - Path=/users,/users/logout,/users/password/reset,/users/password
          filters:
            - PrefixPath=/user
            - Auth=authorization

        - id: aftersales
          uri: http://${other-ip.aftersale}
          predicates:
            - Path=/aftersales/states
          filters:
            - PrefixPath=/aftersale


        - id: aftersale
          uri: http://${other-ip.aftersale}
          predicates:
            - Path=/orderitems/{id}/aftersales,/aftersales,/aftersales/{id},/aftersales/{id}/**
          filters:
            - PrefixPath=/aftersale
            - Auth=authorization


        - id: advertise
          uri: http://${other-ip.advertisement}
          predicates:
            - Path=/advertisement/current,/advertisement/states
          filters:
            - PrefixPath=/advertise

        - id: address
          uri: http://${other-ip.address}
          predicates:
            - Path=/addresses,/addresses/{id}/default,/addresses/{id},/region/{id}/ancestor
          filters:
            - PrefixPath=/address
            - Auth=authorization

        - id: cart
          uri: http://${other-ip.cart}
          predicates:
            - Path=/carts,/carts/{id}
          filters:
            - PrefixPath=/cart
            - Auth=authorization

        - id: share
          uri: http://${other-ip.share}
          predicates:
            - Path=/shares,/skus/{id}/shares,/beshared,/shareactivities
          filters:
            - PrefixPath=/share
            - Auth=authorization

        - id: favorite
          uri: http://${other-ip.favorite}
          predicates:
            - Path=/favorites,/favorites/{id},/favorites/goods/{skuId}
          filters:
            - PrefixPath=/favorite
            - Auth=authorization

        - id: user-freight
          uri: http://${order-ip.freight}
          predicates:
            - Path=/region/{rid}/price
          filters:
            - PrefixPath=/freight
            - Auth=authorization

        - id: all-order
          uri: http://${order-ip.order}
          predicates:
            - Path=/orders/states
          filters:
            - PrefixPath=/order

        - id: user-order
          uri: http://${order-ip.order}
          predicates:
            - Path=/orders,/orders/{id},/orders/{id}/confirm,/orders/{id}/groupon-normal
          filters:
            - PrefixPath=/order
            - Auth=authorization

        - id: all-payment
          uri: http://${order-ip.payment}
          predicates:
            - Path=/payments/states,/payments/patterns
          filters:
            - PrefixPath=/payment

        - id: user-payment
          uri: http://${order-ip.payment}
          predicates:
            - Path=/orders/{id}/payments,/aftersales/{id}/payments,/orders/{id}/refunds,/aftersales/{id}/refunds
          filters:
            - Auth=authorization
            - PrefixPath=/payment

        - id: shop-no-login
          uri: http://${goods-ip}/
          predicates:
            - Path=/shops/states

        - id: groupon-no-login
          uri: http://${goods-ip}/
          predicates:
            - Path=/groupons/states

        - id: groupon-user
          uri: http://${goods-ip}/
          predicates:
            - Path=/groupons
          filters:
            - Auth=authorization

        - id: presales-no-login
          uri: http://${goods-ip}/
          predicates:
            - Path=/presales/states,/presales

        - id: flash-no-login
          uri: http://${goods-ip}/
          predicates:
            - Path=/timesegments/{id}/flashsales,/flashsales/current

        - id: goods-no-login
          uri: http://${goods-ip}/
          predicates:
            - Path=/skus/states,/skus,/skus/{id},/spus/{id}

        - id: goods-user
          uri: http://${goods-ip}/
          predicates:
            - Path=/share/{sid}/skus/{id}
          filters:
            - Auth=authorization

        - id: comments-no-login
          uri: http://${goods-ip}/
          predicates:
            - Path=/comments/states,/skus/{id}/comments

        - id: comments-user
          uri: http://${goods-ip}/
          predicates:
            - Path=/orderitems/{id}/comments,/comments
          filters:
            - Auth=authorization

        - id: category-no-login
          uri: http://${goods-ip}/
          predicates:
            - Path=/categories/{id}/subcategories,/brands

        - id: coupon-no-login
          uri: http://${goods-ip}/
          predicates:
            - Path=/coupons/states,/couponactivities,/couponactivities/{id}/skus

        - id: coupon-user
          uri: http://${goods-ip}/
          predicates:
            - Path=/shops/{shopId}/couponactivities/{id},/coupons,/couponactivities/{id}/usercoupons
          filters:
            - Auth=authorization

  redis:
    host: 172.16.2.67
      # Redis服务器连接端口
    port: 6379
    password: 123456
    # Redis数据库索引（默认为0）
    database: 0
    #连接池最大连接数（使用负值表示没有限制）
    lettuce:
      pool:
        max-active: 100
        # 连接池中的最大空闲连接
        max-idle: 100
        # 连接池中的最小空闲连接
        min-idle: 0
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
    # 连接超时时间（毫秒）
    timeout: 5000


management:
  endpoint:
    gateway:
      enabled: true

privilegegateway:
  jwtExpire: 3600
  refreshJwtTime: 60