server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - HEAD
              - OPTIONS
      routes:
        - id: login
          uri: http://localhost:8081/
          predicates:
            - Path=/users/login,/users
            - Method=POST
          filters:
            - PrefixPath=/user

        - id: adminusers
          uri: http://localhost:8081/
          predicates:
            - Path=/users,/users/logout
            - Method=GET
          filters:
            - PrefixPath=/user
            - Auth=authorization

        - id: aftersale
          uri: http://localhost:8084/
          predicates:
            - Path=/orderitems/{id}/aftersales,/aftersales,/aftersales/{id},/aftersales/{id}/**
          filters:
            - PrefixPath=/aftersale
            - Auth=authorization

        - id: aftersales
          uri: http://localhost:8084/
          predicates:
            - Path=/aftersales/states
          filters:
            - PrefixPath=/aftersale

        - id: advertise
          uri: http://localhost:8085/
          predicates:
            - Path=/advertisement/current,/advertisement/states
          filters:
            - PrefixPath=/advertise

        - id: address
          uri: http://localhost:8082/
          predicates:
            - Path=/addresses,/addresses/{id}/default,/addresses/{id},/region/{id}/ancestor
          filters:
            - PrefixPath=/address
            - Auth=authorization

  redis:
    host: localhost
      # Redis服务器连接端口
    port: 6379
    # Redis数据库索引（默认为0）
    database: 0
    #连接池最大连接数（使用负值表示没有限制）
    lettuce:
      pool:
        max-active: 100
        # 连接池中的最大空闲连接
        max-idle: 100
        # 连接池中的最小空闲连接
        min-idle: 0
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
    # 连接超时时间（毫秒）
    timeout: 5000

management:
  endpoint:
    gateway:
      enabled: true

privilegegateway:
  jwtExpire: 3600
  refreshJwtTime: 60