other-ip:
  customer: localhost:8081
  address: localhost:8082
  advertisement: localhost:8083
  aftersale: localhost:8084
  cart: localhost:8085
  favorite: localhost:8086
  footprint: localhost:8087
  share: localhost:8088
  timesegment: localhost:8089

server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - HEAD
              - OPTIONS
      routes:
        - id: login
          uri: http://${other-ip.customer}
          predicates:
            - Path=/users/login,/users
            - Method=POST
          filters:
            - PrefixPath=/user

        - id: adminusers
          uri: http://${other-ip.customer}
          predicates:
            - Path=/users,/users/logout,users/password/**
          filters:
            - PrefixPath=/user
            - Auth=authorization

        - id: aftersales
          uri: http://${other-ip.aftersale}
          predicates:
            - Path=/aftersales/states
          filters:
            - PrefixPath=/aftersale


        - id: aftersale
          uri: http://${other-ip.aftersale}
          predicates:
            - Path=/orderitems/{id}/aftersales,/aftersales,/aftersales/{id},/aftersales/{id}/**
          filters:
            - PrefixPath=/aftersale
            - Auth=authorization


        - id: advertise
          uri: http://${other-ip.advertisement}
          predicates:
            - Path=/advertisement/current,/advertisement/states
          filters:
            - PrefixPath=/advertise

        - id: address
          uri: http://${other-ip.address}
          predicates:
            - Path=/addresses,/addresses/{id}/default,/addresses/{id},/region/{id}/ancestor
          filters:
            - PrefixPath=/address
            - Auth=authorization

        - id: cart
          uri: http://${other-ip.cart}
          predicates:
            - Path=/carts,/carts/{id}
          filters:
            - PrefixPath=/cart
            - Auth=authorization

        - id: share
          uri: http://${other-ip.share}
          predicates:
            - Path=/shares,/skus/{id}/shares,/beshared,/shareactivities
          filters:
            - PrefixPath=/share
            - Auth=authorization

        - id: favorite
          uri: http://${other-ip.favorite}
          predicates:
            - Path=/favorites,/favorites/{id},/favorites/goods/{skuId}
          filters:
            - PrefixPath=/favorite
            - Auth=authorization
  redis:
    host: 172.16.2.67
      # Redis服务器连接端口
    port: 6379
    password: 123456
    # Redis数据库索引（默认为0）
    database: 0
    #连接池最大连接数（使用负值表示没有限制）
    lettuce:
      pool:
        max-active: 100
        # 连接池中的最大空闲连接
        max-idle: 100
        # 连接池中的最小空闲连接
        min-idle: 0
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
    # 连接超时时间（毫秒）
    timeout: 5000


management:
  endpoint:
    gateway:
      enabled: true

privilegegateway:
  jwtExpire: 3600
  refreshJwtTime: 60